#!/bin/bash

DPI=300

echo -n "Enter Document name: "
read docname

# Create tmpdir
dirname=$(mktemp -d)

# Define options
options="-p --batch=$dirname/%d.png --batch-prompt --mode Color --resolution $DPI"

# Scan
scanimage $options

# Create output filelist
find $dirname -name "*.png" | sort -n > $dirname/filelist

# OCR and convert to pdf
tesseract --oem 1 --dpi $DPI -l deu+eng $dirname/filelist "$HOME/Documents/$docname" pdf

# Cleanup
if [[ "$dirname" == /tmp/tmp.* ]]; then
    echo rm -rf "$dirname"
fi
